AirUberProjeto/src/AirUberProjeto/Models/AutenticacaoViewModels/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AirUberProjeto.Models.AutenticacaoViewModels
{
    /// <summary>
    /// ViewModel para mudar a password.
    /// </summary>
    public class ChangePasswordViewModel
    {

        /// <summary>
        /// A antiga password.
        /// </summary>
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        /// <summary>
        /// A nova password.
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        /// <summary>
        /// Repetição da nova password.
        /// </summary>
        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

AirUberProjeto/src/AirUberProjeto/Models/AutenticacaoViewModels/ForgotPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AirUberProjeto.Models.AutenticacaoViewModels
{
    /// <summary>
    /// ViewModel para o esquecimento de uma password.
    /// </summary>
    public class ForgotPasswordViewModel
    {

        /// <summary>
        /// O email do utilizador que se esqueceu da password.
        /// </summary>
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

AirUberProjeto/src/AirUberProjeto/Models/AutenticacaoViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AirUberProjeto.Models.AutenticacaoViewModels
{
    /// <summary>
    /// View Model para efetuar um login.
    /// </summary>
    public class LoginViewModel
    {

        /// <summary>
        /// Email do utilizador a fazer login
        /// </summary>
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        /// <summary>
        /// Password do utilizador a fazer login
        /// </summary>
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        /// <summary>
        /// Para saber se o utilizador deseja que a sua conta continue logada
        /// </summary>
        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

AirUberProjeto/src/AirUberProjeto/Models/AutenticacaoViewModels/RegisterClienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AirUberProjeto.Models.AutenticacaoViewModels
{
    /// <summary>
    /// View Model responsavel pelo registo de um cliente
    /// </summary>
    public class RegisterClienteViewModel
    {
        /// <summary>
        /// Nome do cliente
        /// </summary>
        [Required]
        [Display(Name = "Primeiro Nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Apelido do cliente
        /// </summary>
        [Required]
        [Display(Name = "Apelido")]
        public string Apelido { get; set; }

        /// <summary>
        /// Email do cliente
        /// </summary>
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// Password do cliente
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// Repetição da password do cliente
        /// </summary>
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }


    }
}

AirUberProjeto/src/AirUberProjeto/Models/AutenticacaoViewModels/RegisterCompanhiaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AirUberProjeto.Models.AutenticacaoViewModels
{
    /// <summary>
    /// View Model responsavel pelo registo da companhia.
    /// </summary>
    public class RegisterCompanhiaViewModel

    {

        /// <summary>
        /// Nome da companhia.
        /// </summary>
        [Required]
        [Display(Name = "Nome Companhia")]
        public string Nome { get; set; }
        /// <summary>
        /// Morada da base da companhia.
        /// </summary>
        [Required]
        [Display(Name = "Morada Escritório")]
        public string Morada { get; set; }
        /// <summary>
        /// Contacto da companhia.
        /// </summary>
        [Required]
        [Display(Name = "Contact")]
        public string Contact { get; set; }
        /// <summary>
        /// Id do pais da companhia
        /// </summary>
        [Required]
        [Display(Name = "Pais")]
        public int PaisId { get; set; }
        /// <summary>
        /// NIf da companhia
        /// </summary>
        [Required]
        [Display(Name = "NIF/NIC Empresa")]
        public string Nif { get; set; }

        /// <summary>
        /// Email do colaborador admin.
        /// </summary>
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// Password para o colaborador admin.
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// Repetição da password para o colaborador admin.
        /// </summary>
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

AirUberProjeto/src/AirUberProjeto/Models/AutenticacaoViewModels/ResetPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AirUberProjeto.Models.AutenticacaoViewModels
{
    /// <summary>
    /// View Model Responsavel para a mudança da password quando o utilizador se esquece da mesma.
    /// </summary>
    public class ResetPasswordViewModel
    {
        /// <summary>
        /// Email do utilizador.
        /// </summary>
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        /// <summary>
        /// Nova password do utilizador.
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        /// <summary>
        /// Repetição da nova password.
        /// </summary>
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        /// <summary>
        /// Codigo enviado pra que o utilizador possa alterar a password.
        /// </summary>
        public string Code { get; set; }
    }
}

AirUberProjeto/src/AirUberProjeto/Controllers/AutenticacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using AirUberProjeto.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using AirUberProjeto.Models;
using AirUberProjeto.Models.AutenticacaoViewModels;
using AirUberProjeto.Services;
using MailKit.Net.Smtp;
using MimeKit;

namespace AirUberProjeto.Controllers
{
    /// <summary>
    /// Controlador responsável pela autenticação dos utilizadores web do sistema.
    /// </summary>
    [Authorize]
    public class AutenticacaoController : Controller
    {
        /// <summary>
        /// User manager que vai permitir utilizar metodos feitos pela windows de forma a controlar os user.
        /// </summary>
        private readonly UserManager<ApplicationUser> _userManager;
        /// <summary>
        /// Manager responsavel pelo tratamento das sessões dos utilizadores.
        /// </summary>
        private readonly SignInManager<ApplicationUser> _signInManager;
        /// <summary>
        /// Server para enviar os emails.
        /// </summary>
        private readonly IEmailSender _emailSender;
        /// <summary>
        /// Logger para cada ação.
        /// </summary>
        private readonly ILogger _logger;
        /// <summary>
        /// O contexto da aplicação para poder aceder a dados.
        /// </summary>
        private readonly AirUberDbContext _context;

        /// <summary>
        /// Construtor do controlador
        /// </summary>
        /// <param name="userManager">O user manager a usar para o controlo de utilizadores</param>
        /// <param name="signInManager">O sign in manager a usar para o controlo de sessões</param>
        /// <param name="emailSender">O email sender a usar para enviar os emails</param>
        /// <param name="loggerFactory">O logger a usar para guardar ações no sistema</param>
        /// <param name="context">O contexto da aplicação</param>
        public AutenticacaoController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailSender emailSender,
            ILoggerFactory loggerFactory,
            AirUberDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _logger = loggerFactory.CreateLogger<AutenticacaoController>();
            _context = context;


            var res = this._userManager.FindByEmailAsync("helpdesk@airuber.com");

            if (res.Result == null)
            {

                Helpdesk h = new Helpdesk
                {
                    Nome = "Helpdesk",
                    Apelido = "Helpdesk",
                    Email = "helpdesk@airuber.com",
                    UserName = "helpdesk@airuber.com"
                };

                var result = this._userManager.CreateAsync(h, "ost:43636/Acc").Result;
                if (result.Succeeded)
                {
                    this._userManager.AddToRoleAsync(h, Roles.ROLE_HELPDESK).Wait();
                }

            }

        }

        //
        // GET: /Account/Login
        /// <summary>
        /// Método responsavel por devover a pagina de login
        /// </summary>
        /// <param name="returnUrl">O url de retorno que é a pagina de onde veio</param>
        /// <returns>A view para efectuar login</returns>
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult AccessDenied(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        /// <summary>
        /// Método responsável pelo pedido de login do utilizador, verificando os dados e autorizando ou não o login.
        /// </summary>
        /// <param name="model">O login model com os dados necessarios para o login</param>
        /// <param name="returnUrl">O url de retorno que é a pagina de onde veio</param>
        /// <returns>A View Login caso seja inválido, um redirecionamento caso seja login válido</returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation(1, "User logged in.");


                    var user = await _userManager.FindByEmailAsync(model.Email);
                    // Get the roles for the user
                    var roles = await _userManager.GetRolesAsync(user);
                    
                    foreach (var role in roles)
                    {

                        switch (role.ToString())
                        {
                            case Roles.ROLE_COLABORADOR_ADMIN:
                                return RedirectToAction(nameof(CompanhiaController.Index), "Companhia");

                            case Roles.ROLE_COLABORADOR:
                                return RedirectToAction(nameof(CompanhiaController.Index), "Companhia");

                            case Roles.ROLE_HELPDESK:
                                return RedirectToAction(nameof(HelpdeskController.Index), "Helpdesk");

                            case Roles.ROLE_CLIENTE:
                                return RedirectToAction(nameof(ClienteController.Perfil), "Cliente");

                        }
                        
                    }


                }
                
                if (result.IsLockedOut)
                {
                    _logger.LogWarning(2, "User account locked out.");
                    return View("Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/Register
        /// <summary>
        /// Metodo responsável pelos pedidos da pagina de registo.
        /// </summary>
        /// <param name="returnUrl">O url de retorno que é a pagina de onde veio</param>
        /// <returns>A view de resgisto</returns>
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }


        //
        // GET: /Account/RegisterCliente
        /// <summary>
        /// Método responsável pelo pedido da pagina de registo de cliente.
        /// </summary>
        /// <param name="returnUrl">O url de retorno que é a pagina de onde veio</param>
        /// <returns>A view de registo do cliente</returns>
        [HttpGet]
        [AllowAnonymous]
        public IActionResult RegisterCliente(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        //
        // POST: /Account/Register
        /// <summary>
        /// Método responsável pelo tratamento de dados para um registo de cliente 
        /// </summary>
        /// <param name="model">Os dados para o registo do cliente</param>
        /// <param name="returnUrl">O url de retorno que é a pagina de onde veio</param>
        /// <returns>Se o registo oi valido retorna um redirecionamento para a home page, caso contrario retorna a view de Registo de Cliente</returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterCliente(RegisterClienteViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                HistoricoTransacoeMonetarias h1 = new HistoricoTransacoeMonetarias();
                ContaDeCreditos conta = new ContaDeCreditos();
                conta.HistoricoTransacoeMonetarias = h1;
                Cliente user = new Cliente { Nome = model.Nome, Apelido = model.Apelido,  UserName = model.Email, Email = model.Email, ContaDeCreditos = conta};
                var result = await _userManager.CreateAsync(user, model.Password);// cria um user com a pw
                if (result.Succeeded)
                {
                    Notificacao notificacao1 = new Notificacao() {Mensagem = "Bem vindo à plataforma", Tipo = Notificacao.TYPE_INFO, Lida = false, UtilizadorId = user.Id};
                    _context.Notificacao.Add(notificacao1);

                    Notificacao notificacao2 = new Notificacao() { Mensagem = "Confirme o seu email", Tipo = Notificacao.TYPE_WARNING, Lida = false, UtilizadorId = user.Id };
                    _context.Notificacao.Add(notificacao2);
                   

                    await _userManager.AddToRoleAsync(user, Roles.ROLE_CLIENTE);//atribui a role

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=532713
                    // Send an email with this link

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/ChangePassword.cshtml
@model AirUberProjeto.Models.AutenticacaoViewModels.ChangePasswordViewModel
@{
    ViewData["Title"] = "Alterar password";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="header">
                <h4 class="title">Alterar palavra-passe</h4>

            </div>
            <div class="content">
                <form asp-controller="Autenticacao" asp-action="ChangePassword" method="post" class="form-horizontal">
                 
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="OldPassword" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="OldPassword" class="form-control" />
                            <span asp-validation-for="OldPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="NewPassword" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="NewPassword" class="form-control" />
                            <span asp-validation-for="NewPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="ConfirmPassword" class="form-control" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-default">Alterar palavra-passe</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
                @section Scripts {
                    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
                }

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/ConfirmEmail.cshtml
@{
    ViewData["Title"] = "Confirm Email";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="header">
                <h4 class="title">Confirmação de email</h4>
            </div>
            <div class="content">
                <div>
                    <p>
                        Obrigado por confirmar a sua conta.  <a class="link" asp-controller="Autenticacao" asp-action="Login">Carregue aqui para fazer Login</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/ConfirmReset.cshtml
@{
    ViewBag.Title = "Confirmar Reset";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="header">
                <h4 class="title">Confirmação de email</h4>
            </div>
            <div class="content">

            @if (@ViewBag.email != null)
            {
                    <form method="post" asp-controller="Autenticacao" asp-action="GenerateNewPassword">
                        <input type="hidden" value="@ViewBag.email" name="email" />
                        <button class="btn">Confirmar</button>
                    </form>
                }
                else
                {
                    <div class="alert alert-danger">
                        Nenhum utilizador valido para esta operação.
                    </div>
                }
            </div>
        </div>
    </div>
</div>

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/ForgotPassword.cshtml
@using AirUberProjeto.Models.AutenticacaoViewModels
@model AirUberProjeto.Models.AutenticacaoViewModels.ForgotPasswordViewModel
@{
    ViewData["Title"] = "Recuperação de password";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            
            <div class="content">

                <form asp-controller="Autenticacao" asp-action="ForgotPassword" method="post" class="form-horizontal">
                    <h4>Recuperar password</h4>
                    <hr />
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Email" class="form-control"/>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-default">Recuperar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/ForgotPasswordConfirmation.cshtml
@{
    ViewData["Title"] = "Confirmação de recuperação de password";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="header">
                <h4 class="title">Recuperação de password</h4>
            </div>
            <div class="content">
                <p>
                    Por favor verifique o seu email.
                </p>
            </div>
        </div>
    </div>
</div>

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/Login.cshtml
@using System.Collections.Generic
@using AirUberProjeto.Models.AutenticacaoViewModels
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@model AirUberProjeto.Models.AutenticacaoViewModels.LoginViewModel
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewBag.Title = "Login";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <section style="text-align: center;margin-top: 30px">
                            <form asp-controller="Autenticacao" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" style="display:inline-block; min-width: 50%">
                            
                                <h4>AirUber</h4>
                                <hr />
                                <div asp-validation-summary="All" class="text-danger"></div>
                                <div class="form-group">

                                    <div class="col-md-12">
                                        <input asp-for="Email" class="form-control" placeholder="Email" style="margin: auto" />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <input asp-for="Password" class="form-control" placeholder="Password" style="margin: auto" />
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <div class="checkbox">
                                            <label asp-for="RememberMe">
                                                <input asp-for="RememberMe" />
                                                @Html.DisplayNameFor(m => m.RememberMe)
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <button type="submit" class="btn btn-default">Entrar</button>
                                    </div>
                                </div>
                                <hr />
                                <p>
                                    <a asp-action="ForgotPassword">Esqueci Senha</a>
                                </p>
                                <p>
                                    Não tem uma conta? <a asp-action="Register" asp-route-returnurl="@ViewData["ReturnUrl"]">Cadastre-se</a>
                                </p>

                            </form>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

                @section Scripts {
                    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
                }

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/RegisterCliente.cshtml
@using AirUberProjeto.Models.AutenticacaoViewModels
@model AirUberProjeto.Models.AutenticacaoViewModels.RegisterClienteViewModel
@{
    ViewBag.Title = "Registar Cliente";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="header">
                <h4 class="title">Registar Cliente</h4>
            </div>
            <div class="container">

                <form asp-controller="Autenticacao" asp-action="RegisterCliente" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" >
                
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nome" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Nome" class="form-control" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Apelido" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Apelido" class="form-control" />
                            <span asp-validation-for="Apelido" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="ConfirmPassword" class="form-control" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-default">Registar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

AirUberProjeto/src/AirUberProjeto/Views/Autenticacao/ResetPasswordConfirmation.cshtml
@{
    ViewData["Title"] = "Reset password confirmation";
}

<div class="content">
    <div class="container-fluid">
        <div class="card">

            <div class="container">
                <h4>Reponha a sua password.</h4>
                <hr />
                <p>
                    A sua password foi alterada. <a asp-controller="Autenticacao" asp-action="Login">Carregue aqui para fazer Login</a>.
                </p>
            </div>
        </div>
    </div>
</div>