AirUberProjeto/src/AirUberProjeto/Models/ClienteViewModels/VerJatoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirUberProjeto.Models.ClienteViewModels
{
    public class VerJatoViewModel
    {
        public IEnumerable<Jato> JatodDisponiveis { get; set; }
        public int AeroportoPartidaId { get; set; }
        public int AeroportoDestinoId { get; set; }
        public DateTime DataPartida { get; set; }
    }
}

AirUberProjeto/src/AirUberProjeto/Models/Companhia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;

namespace AirUberProjeto.Models
{
    /// <summary>
    /// Classe responsável por toda a informação de uma companhia.
    /// </summary>
    public class Companhia
    {
        /// <summary>
        /// Identificador unívoco de uma companhia, sendo chave primária na base de dados.
        /// </summary>
        public int CompanhiaId { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar o nome da companhia.
        /// </summary>
        [Display (Name = "Companhia")]
        [Required]
        public string Nome { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar a morada da companhia.
        /// </summary>
        [Required]
        public string Morada { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar o contacto da companhia.
        /// </summary>
        [Required]
        public string Contact { get; set; }
        /// <summary>
        /// Identificador unívoco do país a que a companhia pertence.
        /// </summary>
        [Display (Name = "País")]
        [Required]
        public int PaisId { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar o NIF da companhia.
        /// </summary>
        [Display(Name = "NIF")]
        [Required]
        public string Nif { get; set; }
        /// <summary>
        /// Identificador unívoco da conta de créditos que pertence à companhia.
        /// </summary>
        [Display (Name ="Crédito")]
        public int ContaDeCreditosId { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar o email da companhia.
        /// </summary>
        [Required]
        public string Email { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar a data de criação da companhia.
        /// </summary>
        [Display(Name = "Data Registo")]
        public DateTime DataCriacao { get; set; }
        /// <summary>
        /// Identificador unívoco do estado que representa a situação actual da companhia no sistema.
        /// </summary>
        [Display (Name = "Estado")]
        public int EstadoId { get; set; }
        /// <summary>
        /// Caminho de onde a imagem de perfil da companhia está localizada no projecto
        /// </summary>
        public string RelativePathImagemPerfil { get; set; }

        /// <summary>
        /// Caminho de onde a imagem de perfil da companhia está localizada no projecto
        /// </summary>
        public string Descricao { get; set; }

        // Propriedades Virtuais
        /// <summary>
        /// Propriedade navegacional responsável por referenciar o país a que uma companhia pertence.
        /// </summary>
        [Display(Name = "País")]
        public virtual Pais Pais { get; set; }
        /// <summary>
        /// Propriedade navegacional responsável por referenciar o estado de uma companhia.
        /// </summary>
        public virtual Estado Estado { get; set; }
        /// <summary>
        /// Propriedade navegacional responsável por referenciar a conta de créditos de uma companhia.
        /// </summary>
        public virtual ContaDeCreditos ContaDeCreditos { get; set; }
        /// <summary>
        /// Propriedade navegacional responsável por referenciar a lista de reservas de uma companhia.
        /// </summary>
        /// <remarks>
        /// Histórico de viagens
        /// </remarks>
        [Display(Name = "Viagens")]
        public virtual ICollection<Reserva> ListaReservas { get; set; }
        /// <summary>
        /// Propriedade navegacional responsável por referenciar a lista de colaboradores que pertence a uma companhia.
        /// </summary>
        [Display(Name = "Número de Colaboradores")]
        public virtual ICollection<Colaborador> ListaColaboradores { get; set; }
        /// <summary>
        /// Propriedade navegacional responsável por referenciar a lista de jatos que pertencem a uma companhia.
        /// </summary>
        [Display(Name = "Número de Jatos")]
        public virtual ICollection<Jato> ListaJatos { get; set; }
        /// <summary>
        /// Propriedade navegacional responsável por referenciar a lista de extras que pertencem a uma companhia.
        /// </summary>
        [Display(Name = "Extras")]
        public virtual ICollection<Extra> ListaExtras { get; set; }



        /// <summary>
        /// Constructor da classe Companhia, é responsável por inicializar a lista de reservas,
        /// de colaboradores, de jatos e extras. É também responsável por inicializar a data de criação para a 
        /// data do momento da criação da companhia. Por omissão também inicializa o EstadoId a 2, que é o 
        /// estado que indica que a companhia está pendente.
        /// </summary>
        public Companhia()
        {
            ListaReservas = new List<Reserva>();
            ListaColaboradores = new List<Colaborador>();
            ListaJatos = new List<Jato>();
            ListaExtras = new List<Extra>();
            DataCriacao = DateTime.Now;
            EstadoId = 2;   // Pendente
            RelativePathImagemPerfil = Path.Combine("images", "perfil-default.jpg");
        }
    }
}

AirUberProjeto/src/AirUberProjeto/Models/CompanhiaViewModels/CompanhiaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AirUberProjeto.Models.CompanhiaViewModels
{
    public class CompanhiaViewModel
    {

        [Required]
        public string Nome { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar a morada da companhia.
        /// </summary>
        [Required]
        public string Morada { get; set; }
        /// <summary>
        /// Propriedade responsável por guardar o contacto da companhia.
        /// </summary>
        [Required]
        public string Contact { get; set; }

        /// <summary>
        /// Descrição da companhia
        /// </summary>
        [Required]
        public string Descricao { get; set; }



        /// <summary>
        /// Identificador único do pais a que pertence a companhia
        /// </summary>
        [Required]
        public int PaisId { get; set; }

        /// <summary>
        /// Número de identificação fiscal da companhia
        /// </summary>
        [Required]
        public string Nif { get; set; }

    }
}

AirUberProjeto/src/AirUberProjeto/Models/CompanhiaViewModels/CriarExtraViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AirUberProjeto.Models.CompanhiaViewModels
{
    /// <summary>
    /// View Model Responsavel por criar um extra
    /// </summary>
    public class CriarExtraViewModel
    {
        /// <summary>
        /// Identificador de um tipo de extra 
        /// </summary>
        public int TipoExtraId { get; set; }
        /// <summary>
        /// Identificador de uma companhia
        /// </summary>
        public int CompanhiaId { get; set; }
        /// <summary>
        /// Nome extra
        /// </summary>
        public string Nome { get; set; }
        /// <summary>
        /// Valor extra
        /// </summary>
        public decimal Valor { get; set; }
    }
}

AirUberProjeto/src/AirUberProjeto/Models/CompanhiaViewModels/CriarJatoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AirUberProjeto.Models.CompanhiaViewModels
{
    /// <summary>
    /// View Model Responsavel por criar um jato
    /// </summary>
    public class CriarJatoViewModel
    {

        /// <summary>
        /// Nome do jato
        /// </summary>
        public string Nome { get; set; }
        /// <summary>
        /// Identificador único do modelo do jato
        /// </summary>
        public int ModeloId { get; set; }
        /// <summary>
        /// Identificador único da companhia a que pertence o jato
        /// </summary>
        public int CompanhiaId { get; set; }
        /// <summary>
        /// Indica se um jato está disponível para viajar
        /// </summary>
        public bool EmFuncionamento { get; set; }       /// ESTA PROPRIEDADE DEVE SAIR, PORQUE NÃO É PARA A COMPANHIA INDICAR, MAS SIM O HELPDESK
        /// <summary>
        /// Identificador único do aeroporto onde o jato se encontra
        /// </summary>
        public int AeroportoId { get; set; }

        /// <summary>
        /// Preço em crédidos por Kilometro
        /// </summary>
        [Display(Name = "Preço em crédidos por Kilometro")]
        public double CreditosPorKilometro { get; set; }

        /// <summary>
        /// Preço base em créditos
        /// </summary>
        [Display(Name = "Preço base em créditos")]
        public double CreditosBase { get; set; }

        /// <summary>
        /// Distância máxima de deslocação em kilometros
        /// </summary>
        [Display(Name = "Distância máxima")]
        public double DistanciaMaxima { get; set; }

        /// <summary>
        /// Velocidade média deslocação em metros/segundo
        /// </summary>
        [Display(Name = "Velocidade média")]
        public double VelocidadeMedia { get; set; }

        /// <summary>
        /// Distância máxima de deslocação em kilometros
        /// </summary>
        [Display(Name = "Tempo de preparação")]
        public double TempoPreparacao { get; set; }


    }
}

AirUberProjeto/src/AirUberProjeto/Models/CompanhiaViewModels/EditarColaboradorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AirUberProjeto.Models.CompanhiaViewModels
{
    /// <summary>
    /// View Model Responsavel por editar um colaborador
    /// </summary>
    public class EditarColaboradorViewModel
    {
        /// <summary>
        /// Identificador de um colaborador
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// Identificador único do colaborador a ser editado
        /// </summary>
        public string ColaboradorId { get; set; }
        /// <summary>
        /// Nome do cliente
        /// </summary>
        [Required]
        [Display(Name = "Primeiro Nome")]
        public string Nome { get; set; }
        /// <summary>
        /// Apelido do cliente
        /// </summary>
        [Required]
        [Display(Name = "Apelido")]
        public string Apelido { get; set; }
        /// <summary>
        /// Email do cliente
        /// </summary>
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        /// <summary>
        /// Companhia
        /// </summary>
        [Display(Name = "Companhia")]
        public int CompanhiaId { get; set; }
        /// <summary>
        /// Indica se um colaborador é administrador ou não
        /// </summary>
        [Display(Name = "É administrador?")]
        public bool IsAdministrador { get; set; }

    }
}

AirUberProjeto/src/AirUberProjeto/Controllers/CreditosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AirUberProjeto.Data;
using AirUberProjeto.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirUberProjeto.Controllers
{

    /// <summary>
    /// Controlador responsável pela gestão de creditos
    /// </summary>
    [Authorize(Roles = Roles.ROLE_CLIENTE + ", " + Roles.ROLE_COLABORADOR +", " + Roles.ROLE_COLABORADOR_ADMIN)]
    public class CreditosController : Controller
    {


        /// <summary>
        /// O contexto da aplicação para poder aceder a dados.
        /// </summary>
        private readonly AirUberDbContext _context;

        /// <summary>
        /// User manager que vai permitir utilizar metodos feitos pela windows de forma a controlar os user.
        /// </summary>
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Construtor do controlador
        /// </summary>
        /// <param name="context">O DB context da aplicação</param>
        /// <param name="userManager">O manager dos utilizadores</param>
        public CreditosController(AirUberDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// A acção index é a ação default do controlador e redireciona para a ação comprar
        /// </summary>
        /// <returns>Retorna a view retornada pela acção comprar</returns>
        [HttpGet]
        [Authorize(Roles = Roles.ROLE_CLIENTE)]
        public IActionResult Index()
        {
            setupNav();
            return RedirectToAction("Comprar");
        }

        public void setupNav()
        {
            string id = _userManager.GetUserAsync(this.User).Result.Id;
            List<Notificacao> notificacoes = _context.Notificacao.Where((n) =>
                    n.UtilizadorId == id
                    && !n.Lida
            ).ToList();
            ViewBag.navegacao = true;
            ViewBag.notificacoes = notificacoes;
        }


        /// <summary>
        /// A acção comprar para poder comprar creditos
        /// </summary>
        /// <returns>Retorna a view Comprar</returns>
        [HttpGet]
        [Authorize(Roles = Roles.ROLE_CLIENTE)]
        public IActionResult Comprar()
        {
            setupNav();
            return View();
        }

        /// <summary>
        /// A ação para poder carregar a conta
        /// </summary>
        /// <param name="amount">O montante a carregar</param>
        /// <returns>Os creditos totais do utilizador</returns>
        [HttpPost]
        [Authorize(Roles = Roles.ROLE_CLIENTE)]
        public string Carregar(int amount)
        {
            setupNav();
            Cliente cliente = (Cliente) _userManager.GetUserAsync(this.User).Result;

            cliente = _context.Cliente.Select(c=>c).Include(c => c.ContaDeCreditos).Include(c => c.ContaDeCreditos.HistoricoTransacoeMonetarias).Single(c => c.Id == cliente.Id);
            cliente.ContaDeCreditos.JetCashActual += amount;
            cliente.ContaDeCreditos.HistoricoTransacoeMonetarias.MovimentosMonetarios.Add(new MovimentoMonetario {Montante = amount, TipoMovimento = TipoMovimento.Carregamento, HistoricoTransacoeMonetariasId = cliente.ContaDeCreditos.HistoricoTransacoeMonetariasId});

            _context.Update(cliente);
            _context.SaveChanges();
            

            return ""+cliente.ContaDeCreditos.JetCashActual;
        }

        /// <summary>
        /// Acao responsavel para devolver uma view com as transaçoes do utilizador
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        [Authorize(Roles = Roles.ROLE_CLIENTE)]
        public IActionResult VerHistoricoTransacoes()
        {
            setupNav();
            Cliente cliente = (Cliente)_userManager.GetUserAsync(this.User).Result;

            cliente = _context.Cliente.Select(c => c).Include(c => c.ContaDeCreditos).Include(c => c.ContaDeCreditos.HistoricoTransacoeMonetarias).Include(c=>c.ContaDeCreditos.HistoricoTransacoeMonetarias.MovimentosMonetarios).Single(c => c.Id == cliente.Id);

            return View(cliente.ContaDeCreditos.HistoricoTransacoeMonetarias.MovimentosMonetarios);
        }

        /// <summary>
        /// Acao responsavel para devolver uma view com as transaçoes do utilizador
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        [Authorize(Roles = Roles.ROLE_COLABORADOR_ADMIN + ", " + Roles.ROLE_COLABORADOR)]
        public IActionResult VerHistoricoTransacoesCompanhia()
        {
            setupNav();
            Colaborador colaborador = (Colaborador)_userManager.GetUserAsync(this.User).Result;

            colaborador = _context.Colaborador.Select(c => c)
                .Include(c => c.Companhia)
                .Include(c => c.Companhia.ContaDeCreditos)
                .Include(c => c.Companhia.ContaDeCreditos.HistoricoTransacoeMonetarias)
                .Include(c => c.Companhia.ContaDeCreditos.HistoricoTransacoeMonetarias.MovimentosMonetarios)
                .Single(c => c.Id == colaborador.Id);

            return View(colaborador.Companhia.ContaDeCreditos.HistoricoTransacoeMonetarias.MovimentosMonetarios);
        }

    }
}

AirUberProjeto/src/AirUberProjeto/Views/Companhia/AdicionarModelo.cshtml
@model AirUberProjeto.Models.Modelo

@{
    ViewData["Title"] = "Criar Modelo";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Criar Modelo</h4>
                        <p class="category">Insira os dados do Modelo</p>
                    </div>

                    <div class="content">
                        <form asp-controller="Companhia" asp-action="AdicionarModelo" method="post" class="form-vertical">
                            <div >
                            
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="TipoJatoId" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <select asp-for="TipoJatoId" class="form-control" asp-items="ViewBag.tipos"></select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Capacidade" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="Capacidade" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Alcance" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="Alcance" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="VelocidadeMaxima" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="VelocidadeMaxima" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="PesoMaximaBagagens" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="PesoMaximaBagagens" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="NumeroMotores" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="NumeroMotores" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="AltitudeIdeal" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="AltitudeIdeal" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="AlturaCabine" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="AlturaCabine" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="LarguraCabine" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="LarguraCabine" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ComprimentoCabine" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="ComprimentoCabine" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Descricao" class="col-md-2 control-label"></label>
                                    <div class="col-md-10">
                                        <input asp-for="Descricao" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Criar" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        </form>
                        
                        <div>
                            <a class="btn" asp-action="VerModelos">Voltar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AirUberProjeto/src/AirUberProjeto/Views/Companhia/ApagarColaborador.cshtml
@model AirUberProjeto.Models.Colaborador

@{
    ViewData["Title"] = "Apagar Colaborador";
    Layout = "_NovoLayout";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Apagar colaborador</h4>
                        <p class="category">Tem a certeza que quer eliminar o colaborador</p>
                    </div>

                    <div class="content">
                        
                        <div>
                           
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Nome)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Nome)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Apelido)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Apelido)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Companhia.Nome)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Companhia.Nome)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.IsAdministrador)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.IsAdministrador)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.DataCriacao)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.DataCriacao)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Email)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Email)
                                </dd>
                            </dl>
                            <form asp-controller="Companhia" asp-action="ApagarColaborador" method="post" class="form-vertical">
                                <input type="hidden" asp-for="Id" />
                                <div class="form-actions no-color">
                                    <input type="submit" style="margin-right: 6px;" value="Apagar" class="btn btn-default" /> 
                                    <a class="btn" asp-action="VerColaboradores">Ver Colaboradores</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AirUberProjeto/src/AirUberProjeto/Views/Companhia/ApagarExtra.cshtml
@model AirUberProjeto.Models.Extra

@{
    ViewData["Title"] = "Apagar Extra";
    Layout = "_NovoLayout";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Apagar Extra</h4>
                        <p class="category">Tem a certeza que quer eliminar o Extra</p>
                    </div>

                    <div class="content">

                        <div>

                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Nome)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Nome)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Valor)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Valor)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Companhia)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Companhia.Nome)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.TipoExtra)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.TipoExtra.Nome)
                                </dd>
                            </dl>
                            <form asp-controller="Companhia" asp-action="ApagarExtra" method="post" class="form-vertical">
                                <input type="hidden" asp-for="ExtraId" />
                                <div class="form-actions no-color">
                                    <input type="submit" style="margin-right: 6px;" value="Apagar" class="btn btn-default" /> 
                                    <a class="btn" asp-action="VerExtras">Ver Extras</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AirUberProjeto/src/AirUberProjeto/Views/Companhia/Creditos.cshtml
@model ContaDeCreditos

    @{
        ViewBag.Title = "Créditos";
    }

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Créditos</h4>
                        <p class="category">Consulte os seus dados monetários</p>
                    </div>
                    <div class="content">
                  
                        <ul class="list-group">
                            <li class="list-group-item">
                                <span class="badge">@Html.Raw(Model.JetCashActual.ToString()) JC</span>
                                Créditos atuais
                            </li>
                        </ul>

                        
                            <a  style="margin-right: 6px" class="btn" asp-area="" asp-controller="Creditos" asp-action="VerHistoricoTransacoesCompanhia">Ver transações</a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>